### ISSUE TITLE
When importing the gradle project into IntelliJ Community Edition and running the Main.tk class

### ISSUE THREAD

**Issue by vejeta** [47deg/ArrowInPractice#4]
@JorgeCastilloPrz , @raulraja Not sure if this is expected when running the project for the first time in IntelliJ
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:71)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:80)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflect_api(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.callFunctionWithInjection(ApplicationEngineEnvironmentReloading.kt:337)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.executeModuleFunction(ApplicationEngineEnvironmentReloading.kt:288)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:265)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:122)
	at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:237)
	at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:97)
	at com.fortysevendeg.arrowinpractice.workshop.MainKt.main(Main.kt:33)
Caused by: java.lang.NoClassDefFoundError: kotlin/coroutines/jvm/internal/CoroutineImpl
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader.findClass(OverridingClassLoader.kt:39)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.fortysevendeg.arrowinpractice.workshop.MainKt$setupAuthentication$1$1.invoke(Main.kt:51)
	at com.fortysevendeg.arrowinpractice.workshop.MainKt$setupAuthentication$1$1.invoke(Main.kt)
	at io.ktor.auth.BasicAuthKt.basic(BasicAuth.kt:48)
	at io.ktor.auth.BasicAuthKt.basic$default(BasicAuth.kt:47)
	at com.fortysevendeg.arrowinpractice.workshop.MainKt$setupAuthentication$1.invoke(Main.kt:49)
	at com.fortysevendeg.arrowinpractice.workshop.MainKt$setupAuthentication$1.invoke(Main.kt)
	at io.ktor.auth.Authentication.configure(Authentication.kt:61)
	at io.ktor.auth.Authentication$Feature.install(Authentication.kt:133)
	at io.ktor.auth.Authentication$Feature.install(Authentication.kt:125)
	at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:59)
	at com.fortysevendeg.arrowinpractice.workshop.MainKt.setupAuthentication(Main.kt:48)
	at com.fortysevendeg.arrowinpractice.workshop.MainKt.setupModule(Main.kt:41)
	... 16 more
Caused by: java.lang.ClassNotFoundException: kotlin.coroutines.jvm.internal.CoroutineImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.ktor.server.engine.OverridingClassLoader$ChildURLClassLoader.findClass(OverridingClassLoader.kt:42)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more

Process finished with exit code 1

```

**Comment by JorgeCastilloPrz** [comment]
Does that happen when running the server? Are you able to run the tests?

Also it requires Kotlin 1.3 now (since yesterday). Are you running it with 1.3? Because the missing class seems to be the CoroutineImpl which was moved by JetBrains to stable packages in 1.3.

**Comment by vejeta** [comment]
It was fixed (probably by) after installing the Kotlin 1.3 plugin
